### ISSUE TITLE
Could not find face_recognition: Travis test fails without any changes

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_smart_apps#60] opened 2015-10-28 14:39 UTC
https://github.com/jsk-ros-pkg/jsk_smart_apps/pull/59

```
...
Failed to build package 'interactive_behavior_201409' because the following command:

# Command to reproduce:
```

**Comment by k-okada** [comment] 2015-10-29 00:49
```
]2;[build] 5/21[[36minteractive_behavior_201409[0m] [31m[1mCMake Error[0m at /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:75 (find_package):[0m [0m[0m
]2;[build] 5/21[[36minteractive_behavior_201409[0m]   Could not find a configuration file for package face_recognition.[0m [0m[0m
]2;[build] 5/21[[36minteractive_behavior_201409[0m] [0m                                                  [0m[0m
]2;[build] 5/21[[36minteractive_behavior_201409[0m]   Set face_recognition_DIR to the directory containing a CMake configuration[0m [0m[0m
]2;[build] 5/21[[36minteractive_behavior_201409[0m]   file for face_recognition.  The file will have one of the following names:[0m [0m[0m
```

**Comment by furushchev** [comment] 2015-10-29 01:13
test on jsk-ros-pkg/jsk_demos passes even without `face_recognition`. Do you know why?
https://github.com/jsk-ros-pkg/jsk_demos/pull/1097

- `face_recognition` is not yet released as deb.
- None in https://github.com/jsk-ros-pkg/jsk_demos/blob/master/.travis.rosinstall

**Comment by wkentaro** [comment] 2015-10-29 01:57
In the first place, why jsk_smart_apps depends on pkgs in jsk_demos?

**Comment by furushchev** [comment] 2015-10-29 02:01
jsk_smart_gui depends on some packages on jsk_demos. 
I think the primary cause is rosdep install all packages by `rosdep --from-paths .`, not specifyng exact package names.
But it need changes a lot, so maybe it is enough just to add `face_recognition` to .rosintall
please answer the question above.

**Comment by wkentaro** [comment] 2015-10-29 02:10
@furushchev

> I think the primary cause is rosdep install all packages by rosdep
--from-paths ., not specifyng exact package names.

what do you mean?

> to above question

I have no idea at this moment.


2015年10月29日木曜日、Furushchev<notifications@github.com>さんは書きました:

> jsk_smart_gui depends on some packages on jsk_demos.
> I think the primary cause is rosdep install all packages by rosdep
> --from-paths ., not specifyng exact package names.
> But it need changes a lot, so maybe it is enough just to add
> face_recognition to .rosintall
> please answer the question above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_smart_apps/issues/60#issuecomment-152051136>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by k-okada** [comment] 2015-10-29 04:01
rosdep-install ignore packages not found: 
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/rosdep-install.sh#L6
```
rosdep install -r -q -n --from-paths . `for i in ${ROS_PACKAGE_PATH//:/\ /}; do if [ -e $i ]; then echo -n $i' '; fi; done` --ignore-src --rosdistro $ROS_DISTRO -y

```
and
```
  -r                    Continue installing despite errors.
```

**Comment by furushchev** [comment] 2015-10-29 04:46
Sorry I misunderstood.

I think the cause is mis detecting of metapackage.
https://github.com/jsk-ros-pkg/jsk_travis/pull/181 will fix this problem.

**Comment by wkentaro** [comment] 2015-11-02 13:29
@furushchev is this fixed?

**Comment by k-okada** [comment] 2015-11-27 01:49
see https://github.com/jsk-ros-pkg/jsk_smart_apps/pull/61/files, 
usually we do not need `find_package(catkin COMPONENT [jsk_demo_packages])` for script packages, since they are mainly used to add `${catkin_INCLUDE_DIRS}` to compile C++ codes. And our `rosdep install` runs with `-r` option, so any depends in package.xml are ignored.

**Closed by k-okada** 2015-11-27 01:49 UTC
